# global_miles_e_commerce_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module GlobalMilesECommerceApi
  # A type of discount.
  class DiscountTypeEnum
    DISCOUNT_TYPE_ENUM = [
      # This type indicates a discount by Global Miles.
      LOYALTY_DISCOUNT = 'loyalty_discount'.freeze,

      # Other type of discounts.
      OTHER = 'other'.freeze
    ].freeze
  end
end
