# global_miles_e_commerce_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module GlobalMilesECommerceApi
  # An order status.
  class OrderStatusEnum
    ORDER_STATUS_ENUM = [
      # Pending
      PENDING = 'pending'.freeze,

      # Refunded
      REFUNDED = 'refunded'.freeze,

      # Processed
      PROCESSED = 'processed'.freeze,

      # Partially Refunded
      PARTIALLY_REFUNDED = 'partially_refunded'.freeze
    ].freeze
  end
end
