# global_miles_e_commerce_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module GlobalMilesECommerceApi
  # A payment status.
  class PaymentStatusEnum
    PAYMENT_STATUS_ENUM = [
      # Started
      STARTED = 'started'.freeze,

      # Completed
      COMPLETED = 'completed'.freeze,

      # Cancelled
      CANCELLED = 'cancelled'.freeze,

      # Refunded
      REFUNDED = 'refunded'.freeze,

      # Used
      USED = 'used'.freeze
    ].freeze
  end
end
